QGA - 8 create user routes
Gruseckis/quiz-game-api pull request #21
Opened 2019-02-18 14:52 UTC by nondante

2019-02-18 15:13 UTC, Gruseckis requested changes

2019-02-18 15:13 UTC, Gruseckis commented on server.js
> +import user from './routes/user';
Make this more meaningful.  What is user? Also name for this route should be better maybe usersRouter?

2019-02-18 15:13 UTC, Gruseckis commented on models/userModel.js
> +  level: {type: String, trim: true, required: true}
This should be enum.

2019-02-18 15:13 UTC, Gruseckis commented on models/userModel.js
> +const getUserByName = async username => UserModel.findOne({username});
Incorrect name for function. You are getting user by username not name.

2019-02-18 15:13 UTC, Gruseckis commented on models/userModel.js
> +
Please remove extra empty lines

2019-02-18 15:13 UTC, Gruseckis commented on models/userModel.js
> +
Please leave only one empty line if you need to

2019-02-18 15:13 UTC, Gruseckis commented on controllers/userController.js
> +import * as UserModel from "../models/userModel";
Why are you importing 8 functions when you only use 3. Please import only functions that you will use.

2019-02-18 15:13 UTC, Gruseckis commented on controllers/userController.js
> +      username: user.username,
you can just send user as payload

2019-02-18 15:13 UTC, Gruseckis commented on controllers/userController.js
> +  const { user } = req;
To be honest we do not have this object attached to req. So your code won'r work.

2019-02-18 15:13 UTC, Gruseckis commented on models/userModel.js
> +import mongoose from 'mongoose';
I would like you to remove this file from PR and make it in separate PR.

2019-02-19 07:38 UTC, KristineZelenivska commented on models/userModel.js
> +  level: {type: String, trim: true, required: true}
level by Default should be "user"
https://mongoosejs.com/docs/defaults.html

2019-02-19 09:49 UTC, Gruseckis requested changes

2019-02-19 09:49 UTC, Gruseckis commented on controllers/userController.js
> +const getAllUsers = async (req,res, next) => {
Please add space after comas

2019-02-19 09:49 UTC, Gruseckis commented
change PR name to be the same as ticket number without spaces

2019-02-19 13:25 UTC, Gruseckis approved these changes

2019-02-19 13:27 UTC, merged